# Site settings
title: Bora Yoon / SW ENGINEER
description: "Bora Yoon / SW ENGINEER"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "윤보라"
resume_title:                   "SW ENGINEER"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yunbora504@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-9023-9424"
# resume_contact_address:         ""

resume_header_contact_info:     "•010-9023-9424 &nbsp &nbsp•yunbora504@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>안녕하세요 의사소통, 책임감, 성장ㆍ발전을 중요하게 생각하는 신입 개발자 윤보라입니다 :)
<br><br>
팀 프로젝트를 통해 의사소통과 각 개인이 맡은 바를 끝까지 해내는 것이 중요하다는 것을 느꼈습니다. 팀원들과의 정확하고 원활한 의사소통을 위해 노력하며, 실제 서비스를 개발함에 있어서 책임감을 가지고 임합니다.
<br><br>
또한 개발자로서 발전하기 위해 꾸준히 공부하고 노력하며, 한 명의 사회 구성원으로서 주변 사람들의 피드백 내용을 적극적으로 수용할 뿐만 아니라, 개인과 구성원 모두 함께 발전하기 위한 피드백에도 적극적입니다.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_projects:        true
# resume_section_skills:          true
resume_section_education:       true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/boraYoon2019"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "https://www.youtube.com/channel/UCkFlQFMb3q1BLJ6FNibMdOQ/"
  resume_youtube_url:         "https://www.youtube.com/channel/UCkFlQFMb3q1BLJ6FNibMdOQ/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
  resume_email:            "yunbora504@gmail.com"
  
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
